development:
  adapter: mysql2
  encoding: utf8
  database: itar_dev
  username: root
  password: 'Ghfdlbycr12mysql'

test:
  adapter: mysql2
  encoding: utf8
  database: itar_test
  username: root
  password: 'Ghfdlbycr12mysql'

production:
  adapter: mysql2
  encoding: utf8
  database: itar_prod
  username: root
  password: 'Ghfdlbycr12mysql'
